GET http://localhost:3001/api/blogs

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "how to train a dragon",
  "author": "kate prima",
  "url": "https://kateprima.com",
  "likes": 3
}